### ISSUE TITLE
Question about Model selection

### ISSUE THREAD

**Issue by xuzhougeng** [dcgerard/updog#13]
Hi, I've been using updog to genotype GBS data for a F2 population with  228 individual.  I  cross two **homozygous diploid** plant (P1 and P2) to get the F1 plant, and generate the F2 population by selfing. The parents (P1, P2) and 228 individual plant was sequenced by GBS technology. 

When I read the help document of updog, I didn't find a model for F2 population but a S1 model.  After I google the difference between F2 and S1,  I get the following answer about F2 and S1.

> however, with an f2 you usually don't know exactly how similar those 2 parents were genetically, while with s1 you know the parent was exactly the same.
> [https://www.autoflower.net/forums/threads/s1-vs-f2.68858/](https://www.autoflower.net/forums/threads/s1-vs-f2.68858/)

So, is it  fine for me to use **s1** for this experiment?

**Comment by dcgerard** [comment]
Hey @xuzhougeng, thanks for trying out `updog`!

An S1 population results from one generation of selfing. Since your F2 population results from selfing **one** individual, you should be able to use `model = "s1"` here.

For more general F2 populations (resulting from using **multiple** F1 individuals as parents), `updog` does not *specifically* support such genotype distributions of F2 populations, but you would still be able to use `model = "norm"` here since this genotype distribution is designed to be flexible enough to fit many genotype distributions.

**Comment by xuzhougeng** [comment]
Thanks for your kindly help!
